from tests.folderA.folderB.raise_exception import error


def multiple_layout_test():
    error()
